{% set name = "autograd" %}
{% set version = "1.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: de743fd368d6df523cd37305dcd171861a9752a144493677d2c9f5a56983ff2f

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-build-isolation . -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - hatchling
  run:
    - python
    - numpy

test:
  imports:
    - autograd
    - autograd.numpy
    - autograd.scipy
    - autograd.scipy.stats
    - autograd.misc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/HIPS/autograd
  license: MIT
  license_family: MIT
  license_file: license.txt
  summary: 'Efficiently computes derivatives of numpy code.'
  description: |
    Autograd can automatically differentiate native Python and Numpy code.
    It can handle a large subset of Python's features, including loops, ifs,
    recursion and closures, and it can even take derivatives of derivatives
    of derivatives.
  dev_url: https://github.com/HIPS/autograd
  doc_url: https://github.com/HIPS/autograd/blob/master/docs/tutorial.md

extra:
  recipe-maintainers:
    - richardotis
    - ericmjl
