{% set version = "1.2" %}
{% set sha256 = "a08bfa6d539b7a56e7c9f4d0881044afbef5e75f324a394c2494de963ea4a47d" %}

package:
  name: autograd
  version: {{ version }}

source:
  fn: autograd-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/autograd/autograd-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10
    - future >=0.15.2
    - scipy >=0.17

  run:
    - python
    - numpy >=1.10
    - future >=0.15.2
    - scipy >=0.17

test:
  imports:
    - autograd
    - autograd.numpy
    - autograd.scipy
    - autograd.scipy.stats

about:
  home: https://github.com/HIPS/autograd
  license: MIT
  summary: 'Efficiently computes derivatives of numpy code.'

extra:
  recipe-maintainers:
    - richardotis
    - ericmjl
