travis:
  secure:
    BINSTAR_TOKEN: mIsEoNmbSPZsQSg0aAq2V6hcny2OCVNRgbyjRpixdvEWZxIFmuvSXFizFYvjaWo6wY+Cys7/yzcvuaeYHeN2zFoR0t4JPralxXv82VN4aIUl3sR1ydiXDLpkF1zh8mtLhhKvwf6eXH/E730ufatC8/p3y0yzESxyhxqhFUvfPGrzVkQKLOgcsHcSoLsemCAvq8T9CHrXh1FdmmM7kt6LE+mlSWHGqKLETxH8m78DpHTBT4RgDjSBnp5QZFM6rvoA2ODzsDDQ73PKErQDUoUXR0WWNCcM07l7oxATkKyvRFPuQHall6yzHstZFuHRp+VWc8hGF2x3zumtuJIt4cIkVHJziwq4Ffq5qlAr+q0Y5gxyQMxnnyHAh3BoKFHLksxvTEjLLhS6V9p1FhF6CVLqB6hbukpeSq+NUQNsX7XM5qW0OR4fL30l3uuMiasE2qUVDr16J71+/txCGDXR8daT3HM0K1z8/JER+roIgp/EMAoTW2vsbh91HYKXaxOjpd/gYQUk8+gKJAA3zAFUx9wg7bWBO5v1twqS3XBPr67cHeCSEXDzO1bUyZguU6IWPZu9lZuNW43nfUl7gCA5itIauwdBNzogxrufBz8H1xxfmgLi/ePm4DBBpbrXs4L/7gvIRGqhS2FANhFGYabY2FvV+dp80f2JvB2bXGC9pBMYb+g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
