travis:
  secure:
    BINSTAR_TOKEN: ip+wIzt5OaOpGIPIZzvk2G+Rf9drm6Fcs5+UJlQD4B2OWM00uwIRUy8FZvyWOiohU9sJcDM57lqz7KaFfY1vSxgvRVz3hm4GNVWuXzuE/bLxFV0vcbuEE76aBSpQdX6B5y5v/YZEZQibUUz4qiK+F4u+I8VL0QJiUBbAfpORgSn//omAvNc7Ubwja6Skv12RXlEfLdvrc6+o6hRcMTT7mGsczj4LN5//M0g3dMmi9E98F0XMm8odDltG5a5HT1/gC2XbQ6Dhd4SJDgltyFHSlIEeQDw54omR4bbufZbptRpoUSjLq6jDqLtQYQdBgT87wTfARjzpzMXfDRwcgcZmmdjQNlFklYycR3XBGeSkR1kSUSb0GTNegSkAWg+MyoGQqZiX8UQ5ocN1NGxGm8L5RVFyhTHl0JqNt6hDtDsZ5Y006YmwfsBZr6YNJuM5Bc3y4g/8076vYCdPDmj8eweYLyJ8+ugs1cYF7c/yg0CQlETXmYMXeqozi8jyJzYvsBcTao6qIta0aMKHXsDyUlme9vyN9DfF8tpZxHI8dshN+dAHLCDuhN5rTUELQ70w7dVbGoI1VOqzcTWZO8H/CIgbmJX2cyU1aA8Xrw3J5O+FEb+Mk18cDzXQJvh841P7i84J0gcZb7DBFFaSs1ADG5RdrwF4CVRtOdIq/GJRIrT4AW4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
